#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID

echo $$ > /var/run/myscript.pid

function sigterm_handler()
{
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	
	exit 0
}

function sigquit_handler()
{
    rm -f /var/run/myscript.pid
    exit 0
}

function sigint_handler()
{
	echo "Y U no love me?!"
}

trap sigterm_handler SIGTERM
trap sigint_handler SIGINT
trap sigquit_handler SIGQUIT

while (true);
do
	echo "To infinity and beyond"
	sleep 2
done
