#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:
hour=0
min=1
while ((hour < 13));
do
	echo "Hour: $hour"
	while ((min<60)); do
		echo "$min"
		((min+=1))
	done
	((hour+=1))
	((min=1))
done
	
